name: PushToCephProduction

# Controls when the action will run.
on:
  # Triggers the workflow on push events to main branch
  push:
    branches: [ main ]
    paths:
      - 'content/**'
      - 'config/**'
      - 'layouts/**'
      - 'assets/**'
      - '.github/workflows/deploy-ceph-prod.yml'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build job - Builds the Hugo site and uploads artifacts
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
          repository: OpenizePtyLtd/fileformat.ai
          token: ${{ secrets.REPO_TOKEN }}
          submodules: true  # Fetch Hugo themes
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
          hugo-version: '0.125.7'
          extended: true

    - name: Build Site
      run: hugo --environment production -b "https://www.fileformat.ai/" --minify --cleanDestinationDir 

    - name: Deploy to Ceph Production
      run: |
        hugo deploy --target production-ceph --environment production --maxDeletes -1 --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_SECRET_KEY }}

    - name: Purge Bunny CDN cache
      if: github.event_name != 'pull_request'
      env:
        BUNNYNET_ACCESSKEY: ${{ secrets.BUNNYNET_ACCESSKEY }}
      run: |
        curl --version
        echo Purging https://www.fileformat.ai
        curl -siG -H "X-Api-Key: $BUNNYNET_ACCESSKEY" --data-urlencode "url=https://www.fileformat.ai/*" "https://api.dynabic.com/bn/purge?async=true"
